backend = "glx";  # Set the backend to glx
vsync = true;     # Enable vsync

# Shadow settings
shadow = true;  # Enable shadows
shadow-radius = 12;  # Shadow blur radius
shadow-offset-x = -15;  # Shadow offset X
shadow-offset-y = -15;  # Shadow offset Y
shadow-opacity = 0.7;  # Shadow opacity

# Fading settings
fading = true;  # Enable fading
fade-in-step = 0.03;  # Fade in step
fade-out-step = 0.03;  # Fade out step
fade-exclude = [ "class_g = 'Notification'" ];  # Exclude notifications from fading

# Transparency settings
active-opacity = 0.8;  # Opacity of active windows
inactive-opacity = 0.9;  # Opacity of inactive windows
frame-opacity = 0.7;  # Opacity of window frames

# Blur settings
blur-background = true;  # Enable background blur
blur-method = "dual_kawase";  # Blur method
blur-strength = 5;  # Strength of the blur

# Other settings
detect-client-opacity = true;  # Detect client opacity
no-fading-openclose = true;  # Disable fading for opening/closing windows
wintypes:
{
    tooltip = { fade = false; shadow = false; };  # Tooltips without fade and shadow
    dropdown_menu = { fade = false; shadow = false; };  # Dropdown menus without fade and shadow
}

# Exclude certain windows from effects
opacity-rule = [
    "100:class_g = 'dunst'",  # Dunst notifications
    "100:class_g = 'Gimp'",   # GIMP
    "100:class_g = 'mpv'",
    "100:class_g = 'Zathura'",
    "100:class_g = 'feh'",
    "100:class_g = 'firefox'",
    "100:class_g = 'Tor Browser'",
    "100:class_g = 'okular'",
];

